"""empty message

Revision ID: 167012f78b52
Revises: 8c9f42ae7215
Create Date: 2021-12-18 16:18:30.434277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167012f78b52'
down_revision = '8c9f42ae7215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
